# @package _global_

# Domain adaptation Mnist -> USPS
# This config only support `federalize` to create the dataset.
# Do not change the order.
dataset:
  name: "comb/Digit"
  meta_fed_ds: federalize  # federalize | extend (default)
  #  meta_datasets: ["Mnist", "MnistM"]
#  comb_mode: "sep"  # sep: Each user only have a single domain data. mix: Each user has all domain.
#  total_n_user: 20
  meta_datasets:
    - name: SVHN  # target domain
      seed: 42
      n_user: 1
      n_class: 10
      class_stride: 2
      partition_mode: uni
      min_n_sample_per_share: 2  # num sample per class per user shard
      max_n_sample_per_share: -1
      max_n_sample_per_class: -1
      n_channel: 3  # 1 or 3
      user_data_format: tensor
      random_crop_rot: True
      resize: 28
    - name: Mnist  # source domain
      seed: 42
      n_user: 1
      n_class: 10
      class_stride: 2
      partition_mode: uni
      min_n_sample_per_share: 2 # num sample per class
      max_n_sample_per_share: -1
      max_n_sample_per_class: -1
      n_channel: 3  # 1 or 3
      user_data_format: tensor
