# @package _global_

# 1to1 Domain adaptation on Office31 dataset
# 1 source user vs 3 target user
# Do not change the order.
dataset:
  name: "comb/Office31_X2X_1s_3t"
  meta_fed_ds: federalize
  meta_datasets:
    - name: Office31W  # target domain: Webcam
      seed: 42
      n_user: 3
      n_class: 15
      class_stride: 10
      min_n_sample_per_share: 2  # num sample per class per user shard
      max_n_sample_per_share: -1
      max_n_sample_per_class: -1
      user_data_format: dataset
      feature_type: images
      partition_mode: uni
    - name: Office31A  # source domain: Amazon
      seed: 42
      n_user: 1
      n_class: 31
      class_stride: 1
      min_n_sample_per_share: 2 # num sample per class
      max_n_sample_per_share: -1
      max_n_sample_per_class: -1
      user_data_format: dataset
      feature_type: images
      partition_mode: uni
