# @package _group_
name: FedAvg
alg: FedAvg  # server alg
num_users: 20  # Number of Users per global round
beta: 1. # Average moving parameter for pFedMe, or Second learning rate of Per-FedAvg
share_mode: all
privacy:
  enable: false
  # Add only on use
#    user_clip_norm: -1  # User-DP clip norm (layer wise)
#    user_dp_sigma: -1  # User-DP noise sigma
