# @package _group_
name: Adult2W
seed: 42
n_user: 1
n_class: 2
class_stride: 1
partition_mode: uni
min_n_sample_per_share: 2 # num sample per class
max_n_sample_per_share: -1
max_n_sample_per_class: 1000  # equivalent to -1 in practice
user_data_format: tensor
n_sample_per_class: -1  # test size per class